# Generated by Django 5.1.6 on 2025-03-14 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tg_id', models.CharField(db_index=True, default='blank_id', max_length=255)),
                ('is_handling', models.BooleanField(default=False)),
                ('complaint', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tg_id',), name='unique_client')],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tg_id', models.CharField(db_index=True, default='blank_id', max_length=255)),
                ('is_busy', models.BooleanField(db_index=True, default=False)),
                ('current_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tg_id',), name='unique_admin')],
            },
        ),
    ]
